from typing import Protocol, Any

class QueueProtocol(Protocol):
    def enqueue(self, item: Any) -> None: ...
    def dequeue(self) -> Any: ...
    def peek(self) -> Any: ...
    def size(self) -> int: ...
